default: &default
  adapter: postgresql
  username: postgres
  password: pwgqsyx2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: thinknetica_dev

test:
  <<: *default
  database: thinknetica_test