# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e1f9ce9263caa73c2b10716c4a49def346155125a8569a87d01ce8f03921f19647fb395827ec4b3b7ec7c173f4c0895a225a8e37a5afc967a8abba683fb2fa0

test:
  secret_key_base: 0f2544bb18b90d13583a99df6e3058df23df6e44d390756f8433c8059b9b12e6b1cf65ba70bc7b5fb83eb426e8cc8087f0036200d05544488eaf46f9e0183862

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
